import { NextRequest, NextResponse } from 'next/server';
import puppeteer from 'puppeteer';

export async function POST(req: NextRequest) {
  try {
    const { content, title } = await req.json();

    if (!content || !title) {
      return new NextResponse('Missing content or title', { status: 400 });
    }

    // Markdown-like to HTML conversion (simplified version of the one in pdf-utils.ts)
    const htmlContent = content
      .replace(/^# (.*$)/gm, '<h1 style="font-size: 24pt; color: #0f172a; font-weight: 800; margin-bottom: 24pt; border-bottom: 1px solid #e2e8f0; padding-bottom: 12pt;">$1</h1>')
      .replace(/^## (.*$)/gm, '<h2 style="font-size: 18pt; color: #1e293b; font-weight: 700; margin-top: 32pt; margin-bottom: 16pt;">$1</h2>')
      .replace(/^### (.*$)/gm, '<h3 style="font-size: 14pt; color: #334155; font-weight: 600; margin-top: 24pt; margin-bottom: 8pt;">$1</h3>')
      .replace(/^\|(.+)\|$\n^\|([-: |]+)\|$\n((?:^\|(.+)\|$\n?)+)/gm, (match: string, header: string, separator: string, body: string) => {
        const rows = body.trim().split('\n').map((row: string) => {
          const cells = row.split('|').filter(Boolean).map((cell: string) => `<td style="border: 1px solid #e2e8f0; padding: 8pt; font-size: 9pt;">${cell.trim()}</td>`).join('');
          return `<tr style="border-bottom: 1px solid #e2e8f0;">${cells}</tr>`;
        });
        const headerCells = header.split('|').filter(Boolean).map((cell: string) => `<th style="border: 1px solid #e2e8f0; padding: 8pt; background: #f8fafc; font-weight: 600; text-align: left; font-size: 9pt;">${cell.trim()}</th>`).join('');
        return `<table style="width: 100%; border-collapse: collapse; margin: 16pt 0; border: 1px solid #e2e8f0;"><thead><tr>${headerCells}</tr></thead><tbody>${rows.join('')}</tbody></table>`;
      })
      .replace(/\*\*(.*)\*\*/g, '<strong style="font-weight: 600; color: #0f172a;">$1</strong>')
      .replace(/\*(.*)\*/g, '<em style="font-style: italic;">$1</em>')
      .replace(/`(.*)`/g, '<code style="background: #f1f5f9; padding: 2pt 4pt; border-radius: 4pt; font-family: monospace; font-size: 90%; color: #ef4444;">$1</code>')
      .replace(/^\- (.*$)/gm, '<li style="margin-bottom: 4pt; margin-left: 20pt;">$1</li>')
      .replace(/\n\n/g, '</div><div style="margin-bottom: 12pt;">')
      .replace(/\n/g, '<br/>');

    const fullHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');
          body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            margin: 0;
            padding: 0;
            background: white;
          }
          .container {
            padding: 20mm;
            max-width: 190mm;
            margin: 0 auto;
          }
          .header {
            margin-bottom: 40pt;
            text-align: center;
          }
          .report-type {
            font-size: 10pt;
            color: #64748b;
            margin-bottom: 8pt;
            text-transform: uppercase;
            letter-spacing: 0.05em;
          }
          .title {
            margin: 0;
            font-size: 28pt;
            font-weight: 800;
            color: #0f172a;
          }
          .divider {
            margin-top: 12pt;
            height: 2pt;
            width: 60pt;
            background: #3b82f6;
            margin-left: auto;
            margin-right: auto;
          }
          .meta {
            margin-top: 16pt;
            color: #64748b;
            font-size: 10pt;
          }
          .content {
            color: #334155;
            font-size: 11pt;
          }
          .footer {
            margin-top: 40pt;
            padding-top: 20pt;
            border-top: 1px solid #f1f5f9;
            font-size: 9pt;
            color: #94a3b8;
            text-align: center;
          }
          pre, code {
            font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
          }
          table {
            page-break-inside: auto;
          }
          tr {
            page-break-inside: avoid;
            page-break-after: auto;
          }
          thead {
            display: table-header-group;
          }
          tfoot {
            display: table-footer-group;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="report-type">Security Assessment Report</div>
            <h1 class="title">${title}</h1>
            <div class="divider"></div>
            <p class="meta">Generated by Kali AI Platform &bull; ${new Date().toLocaleDateString(undefined, { dateStyle: 'long' })}</p>
          </div>
          <div class="content">
            <div>${htmlContent}</div>
          </div>
          <div class="footer">
            This report is generated for security educational purposes. Always ensure you have proper authorization before testing.
          </div>
        </div>
      </body>
      </html>
    `;

    let browser;
    try {
      browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      });

      const page = await browser.newPage();
      await page.setContent(fullHtml, { waitUntil: 'networkidle0' });
      
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '10mm',
          right: '10mm',
          bottom: '10mm',
          left: '10mm',
        },
      });

      return new NextResponse(pdfBuffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${title.replace(/[^\w\s]/gi, '').replace(/\s+/g, '_')}.pdf"`,
        },
      });
    } finally {
      if (browser) await browser.close();
    }
  } catch (error) {
    console.error('PDF generation error:', error);
    return new NextResponse('Internal Server Error', { status: 500 });
  }
}
